Fix issue #50: Run integration test in integration-test phase, not test
- introduce failsafe-plugin
-- surefire-junit47 is optional, but may be helpful later

- integration test now uses the already packaged jar instead of
  rebuilding the entire project which leads to strange
  NoClassDefFoundErrors regarding StaticLoggerBinder$1
-- introduction of separate maven repo is required for this
   which is cleaner anyway